H2STORE test cases
OPM/opm-tests pull request #919
Opened 2023-03-15 11:24 UTC by svenn-t

Depends on https://github.com/OPM/opm-common/pull/3445 and https://github.com/OPM/opm-simulators/pull/4528 
These test cases are the same as for CO2STORE, but with H2STORE keyword enabled.

2023-03-15 12:30 UTC, goncalvesmachadoc commented on H2STORE_GW.DATA
> +   CO2STORE GAS-WATER DISGASW
CO2STORE -> H2STORE

2023-03-15 12:30 UTC, goncalvesmachadoc commented on H2STORE_GW.DATA
> +-- Copyright (C) 2021 NORCE
2021 -> 2023

2023-03-15 12:31 UTC, goncalvesmachadoc commented on H2STORE_GW.DATA
> +
0.7/ 35-40g/l  -> 35-40g /kg -> 0.63-0.72 mol/g
->
0.7/ -- 35-40g/l  -> 35-40g /kg -> 0.63-0.72 mol/g

2023-03-15 13:09 UTC, bska commented on H2STORE_GW.DATA
This file (`H2STORE_GW.DATA`) appears to have been added **outside** of the new `h2store` directory&mdash;i.e., in the top-level `opm-tests` directory.  Is that intentional?  If not I'd prefer if it were moved into the `h2store` directory.

2023-03-15 13:37 UTC, svenn-t commented on H2STORE_GW.DATA
> +   CO2STORE GAS-WATER DISGASW
Corrected, thanks!

2023-03-15 13:37 UTC, svenn-t commented on H2STORE_GW.DATA
> +-- Copyright (C) 2021 NORCE
Corrected, thanks!

2023-03-15 13:38 UTC, svenn-t commented on H2STORE_GW.DATA
> +
Corrected, thanks!

2023-03-15 13:38 UTC, svenn-t commented on H2STORE_GW.DATA
Sorry, that was not intentional. Moved it inside h2store directory now.

2023-09-20 09:49 UTC, totto82 commented
@bska and @goncalvesmachadoc Can this be merged now? I would like to get this in before merging the update on the H2STORE option to make sure we have proper tests for the new functionality.

2023-09-20 10:23 UTC, bska reviewed
> Can this be merged now?

I don't see why not as most of this is straightforward.  I'll let @goncalvesmachadoc have the final say, though, because I don't know enough about the physics here to know if I'm missing some subtle detail.

2023-09-20 11:26 UTC, goncalvesmachadoc requested changes

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE.DATA
> +
Please add short description of the case.

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE.DATA
> +NOECHO
Remove NOECHO.

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE_DIFFUSIVE.DATA
> +
Please add short description of the case.

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE_DIFFUSIVE.DATA
> +NOECHO
Remove NOECHO.

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE_DISGAS.DATA
> +
Please add short description of the case.

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE_DISGAS.DATA
> +NOECHO
Remove NOECHO.

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE_ENERGY.DATA
> +
Please add short description of the case.

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE_ENERGY.DATA
> +NOECHO
Remove NOECHO.

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE_GW.DATA
> +NOECHO
Remove NOECHO.

2023-09-20 11:26 UTC, goncalvesmachadoc commented on h2store/H2STORE_GW.DATA
> +100*1
Is it necessary to have a longer run for this case in particular? All other cases are 30*1.

2023-09-20 12:35 UTC, merged