Add WELTRAJ test case
OPM/opm-tests pull request #940
Opened 2023-04-11 15:22 UTC by goncalvesmachadoc

Depends on https://github.com/OPM/opm-common/pull/3465

2023-05-14 08:51 UTC, tskille requested changes
Two minor comments regarding ECHO and NOECHO. 

I would also suggest that we move this test to a new folder weltraj and perhaps rename the test to WELTRAJ-01.DATA

2023-05-14 08:51 UTC, tskille commented on spe1/SPE1CASE1_WELTRAJ.DATA
> +NOECHO
Keyword NOECHO is not supported. I'm in favor for removing this from the deck.

2023-05-14 08:51 UTC, tskille commented on spe1/SPE1CASE1_WELTRAJ.DATA
> +ECHO
This can hopefully also be removed as we are not supporting this.

2023-05-18 08:06 UTC, tskille commented
I see now that this PR includes changes to [co2store/CO2STORE_GASWAT.DATA](https://github.com/OPM/opm-tests/pull/940/commits/496f5aeb0ce136427e42b76463ba13c307042fcc#diff-23c8d86200860645c28eae78514c79ad03b72b65a9fa12a62fb56e846ffc4ea9) . Is this intentional ? 

Apart from this I'm happy to merge this now.

2023-05-18 09:34 UTC, goncalvesmachadoc commented
Thank you for noticing. Problem solved.

2023-05-18 10:09 UTC, tskille approved these changes
Excellent, merging now

2023-05-18 10:09 UTC, merged